# Generated by Django 4.2.5 on 2023-10-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_back_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back',
            name='cover',
            field=models.ImageField(upload_to='images', verbose_name='Изображение товара'),
        ),
    ]
