# Generated by Django 4.2.5 on 2023-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_back_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение товара'),
        ),
    ]
